version: 0.0
os: linux
files:
  - source: /frontend/Frontend/build/*
    destination: /var/www/frontend
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
