version: 0.2
run-as: root

phases:
  install:
    commands:
      - apt update -y
      - apt install nginx -y
      - apt install nodejs -y
      - apt install npm -y
  pre_build:
    commands:
      - cd Frontend
      - node -v || curl -sL https://deb.nodesource.com/setup_14.x | sudo bash - && apt -y install nodejs
  build:
    commands:
      - npm install
      - npm run build
      
artifacts:
   files:
      - '**/*'
   discard-paths: no
   base-directory: Frontend/build
